from __future__ import annotations

SCREEN_WIDTH = 320
SCREEN_HEIGHT = 568
SKY_BOTTOM_Y = 378
GROUND_TOP_Y = 378
FPS = 60

WINDOW_TITLE = "MOKUMOKU Prototype"

CAMERA_LEFT_YAW = -32.0
CAMERA_FRONT_YAW = 0.0
CAMERA_RIGHT_YAW = 32.0
CAMERA_PITCH = 14.0
CAMERA_DISTANCE = 460.0
CAMERA_FOCAL_LENGTH = 420.0
CAMERA_TRANSITION_SECONDS = 0.60
NEAR_CLIP = 1.0
VIEWPORT_CENTER_X = SCREEN_WIDTH / 2
HORIZON_Y = 308.0
TOUCH_HIT_PADDING = 6.0
HIT_DEPTH_EPSILON = 2.0
TAP_ATTACH_DISTANCE = 42.0
CONNECTED_TAP_SCREEN_BLEND = 0.62
CAMERA_BUTTON_WIDTH = 46
CAMERA_BUTTON_HEIGHT = 36
CAMERA_BUTTON_MARGIN_X = 16
CAMERA_BUTTON_Y = GROUND_TOP_Y + 22

CLOUD_DEPTH_MIN = -24.0
CLOUD_DEPTH_MAX = 24.0
CHILD_DEPTH_OFFSET_MAX = 6.0

MAX_LINEAGES_ACTIVE = 1
MAX_CLUSTERS = 8
MAX_NODES_TOTAL = 128
MAX_NODES_PER_CLUSTER = 96
MAX_EDGES_TOTAL = 320
MAX_NODE_DEGREE = 5

RADIUS_SCALE = 3.1
MIN_NODE_RADIUS = 4.0
MAX_NODE_RADIUS = 22.0

SEED_MASS = 9.0
SEED_DENSITY = 1.0
TAP_MASS_GAIN = 6.0
TAP_ACTIVATION_GAIN = 0.45
LONG_PRESS_SECONDS = 0.40
PRESS_SLOP_PX = 7.0
BASE_CONDENSATION_GAIN = 2.4
BASE_DENSITY_GAIN = 0.18
DRAG_START_DISTANCE = 6.0
FLICK_MIN_DISTANCE = 24.0
FLICK_MIN_SPEED = 420.0
EDGE_BREAK_RATIO = 2.2
MERGE_DISTANCE = 18.0
MERGE_MAX_RELATIVE_SPEED = 30.0
SPRING_FOLLOW_RATIO = 0.20
EDGE_REST_RADIUS_RATIO = 0.66
EDGE_COHESION_RATE = 8.0
EDGE_COMPRESSION_RATIO = 0.48
CLOUD_CLUSTER_WOBBLE_OFFSET_PX = 0.35
CLOUD_LOCAL_WOBBLE_OFFSET_PX = 0.0
CLOUD_CLUSTER_WOBBLE_PERIOD_X = 14.0
CLOUD_CLUSTER_WOBBLE_PERIOD_Y = 11.0
CLOUD_LOCAL_WOBBLE_PERIOD_X = 18.0
CLOUD_LOCAL_WOBBLE_PERIOD_Y = 15.0
CLOUD_BRIDGE_MIN_STRAIN = 1.08
CLOUD_BRIDGE_MAX_STRAIN = 1.9

INCUBATION_START_SECONDS = 5.0
INCUBATION_GAIN_RATE = 0.22
NOISE_DECAY_RATE = 0.18
SMOOTHING_RATE = 0.16
REDUNDANT_MERGE_DISTANCE = 5.5
REDUNDANT_MERGE_MIN_UNTOUCHED = 7.0
NATURAL_MASS_DECAY_START_SECONDS = 11.0
NATURAL_MASS_DECAY_RATE = 2.8
RETENTION_MAX_NODE_DEGREE = 3
RETENTION_GROWN_MASS = 18.0
RETENTION_DECAY_REDUCTION = 0.72
RETAINED_MASS_DECAY_MIN_RATIO = 0.24
PRUNE_MASS_THRESHOLD = 2.4
PRUNE_FADE_SECONDS = 1.4

STAGE_X_MIN = 0.0
STAGE_X_MAX = 4800.0
STAGE_Z_MIN = -120.0
STAGE_Z_MAX = 120.0
BASE_STAGE_SPEED = 10.0

LOCAL_X_MIN = -150.0
LOCAL_X_MAX = 150.0
MIN_CLOUD_Y = 64.0
MAX_CLOUD_Y = 300.0

PYXEL_RESOURCE_PATH = "assets/mokumoku.pyxres"

COLOR_TRANSPARENT = 0
COLOR_SKY = 1
COLOR_GROUND = 12
COLOR_UI = 14
